language: python

sudo: false

cache:
  - pip

python:
 - "2.7"

env:
 - DJANGO_VERSION=1.8.14
 - DJANGO_VERSION=1.9.9
 - DJANGO_VERSION=1.10.3

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database calaccess_processed;' -U postgres

script:
 - flake8 calaccess_processed
 - coverage run example/manage.py test calaccess_processed

after_success:
 - coveralls
