language: python
sudo: false

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.8.8
 - DJANGO_VERSION=1.9.1

install:
 - pip install -r requirements_dev.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - mysql -e 'create database calaccess_processed;'

script:
 - pep8 calaccess_processed
 - pyflakes calaccess_processed
 - coverage run example/manage.py test calaccess_processed

after_success:
 - coveralls
